import { date, numeric, pgTable, serial, varchar } from "drizzle-orm/pg-core";

export const agent = pgTable("agent", {
  idx: serial("agent_id").primaryKey(),
  agent_id: varchar("agent_id", { length: 50 }),
  agent_name: varchar("agent_name", { length: 70 }).notNull(),
  agent_type: numeric("agent_type", { precision: 10, scale: 0 }).notNull(),
  tel_no: numeric("tel_no", { precision: 10, scale: 0 }),
  mobile_no: numeric("mobile_no", { precision: 10, scale: 0 }).notNull(),
  fax_no: numeric("fax_no", { precision: 10, scale: 0 }),
  postal_add: varchar("postal_add", { length: 30 }),
  town: varchar("town", { length: 20 }),
  phy_loc: varchar("phy_loc", { length: 20 }),
  email: varchar("email", { length: 30 }).notNull(),
  contact_person: varchar("contact_person", { length: 30 }),
  contact_mobile: varchar("contact_mobile", { length: 30 }),
  contact_tel: varchar("contact_tel", { length: 30 }),
  user_id: varchar("user_id", { length: 100 }),
  date_entered: date("date_entered").defaultNow(),
  unit_manager: varchar("unit_manager", { length: 30 }),
  branch: varchar("branch", { length: 30 }).notNull(),
  account_code: varchar("account_code", { length: 20 }),
  uploaded: numeric("uploaded", { precision: 10, scale: 0 }),
  commiss_rate: numeric("commiss_rate", { precision: 10, scale: 0 }).notNull(),
  whtx_rate: numeric("whtx_rate", { precision: 10, scale: 0 }).notNull(),
  runoff: varchar("runoff", { length: 2 }).notNull(),
  agn_status: varchar("agn_status", { length: 10 }).notNull(),
  unit: varchar("unit", { length: 30 }),
});
