import {
  date,
  integer,
  numeric,
  pgTable,
  serial,
  timestamp,
  varchar,
} from "drizzle-orm/pg-core";

// BILLS
export const bills = pgTable("bills", {
  id: serial("id").primaryKey(),
  claim_no: varchar("claim_no", { length: 25 }),
  invoice_no: varchar("invoice_no", { length: 150 }),
  claim_form_no: varchar("claim_form_no", { length: 25 }),
  provider: numeric("provider", { precision: 5, scale: 0 }),
  member_no: varchar("member_no", { length: 20 }),
  service: numeric("service", { precision: 2, scale: 0 }),
  claim_nature: numeric("claim_nature", { precision: 2, scale: 0 }),
  referred_by: numeric("referred_by", { precision: 5, scale: 0 }),
  ip_doctor: numeric("ip_doctor", { precision: 5, scale: 0 }),
  invoice_date: date("invoice_date"),
  invoiced_amount: numeric("invoiced_amount", { precision: 10, scale: 2 }),
  deduction_amount: numeric("deduction_amount", { precision: 10, scale: 2 }),
  deduction_reason: numeric("deduction_reason", { precision: 5, scale: 0 }),
  amount_payable: numeric("amount_payable", { precision: 10, scale: 2 }),
  deduction_notes: varchar("deduction_notes", { length: 50 }),
  paid: numeric("paid", { precision: 1, scale: 0 }),
  voucher_no: varchar("voucher_no", { length: 10 }),
  payment_no: varchar("payment_no", { length: 10 }),
  sent_to_re: numeric("sent_to_re", { precision: 1, scale: 0 }),
  batch_no: varchar("batch_no", { length: 15 }),
  payment_date: date("payment_date"),
  user_id: varchar("user_id", { length: 100 }),
  date_entered: timestamp("date_entered").notNull().defaultNow(),
  refund: numeric("refund", { precision: 1, scale: 0 }),
  claimed_cancelled: numeric("claimed_cancelled", { precision: 1, scale: 0 }),
  anniv: numeric("anniv", { precision: 3, scale: 0 }),
  capped: numeric("capped", { precision: 1, scale: 0 }),
  admin_fee: numeric("admin_fee", { precision: 10, scale: 2 }),
  fund: numeric("fund", { precision: 1, scale: 0 }),
  re_insurer: numeric("re_insurer", { precision: 2, scale: 0 }),
  date_received: date("date_received"),
  vet_status: numeric("vet_status", { precision: 1, scale: 0 }),
  entry_notes: varchar("entry_notes", { length: 30 }),
  voucher_user: varchar("voucher_user", { length: 100 }),
  bill_serial_no: varchar("bill_serial_no", { length: 20 }),
  contra_amt: numeric("contra_amt", { precision: 10, scale: 2 }),
  corp_expense: numeric("corp_expense", { precision: 1, scale: 0 }),
  pre_auth_no: numeric("pre_auth_no", { precision: 7, scale: 0 }),
  voucher_date: date("voucher_date"),
  in_excess: numeric("in_excess", { precision: 1, scale: 0 }),
  proxy_payee: varchar("proxy_payee", { length: 50 }),
  member_id: varchar("member_id", { length: 20 }),
  import: numeric("import", { precision: 1, scale: 0 }),
  corp_id: varchar("corp_id", { length: 10 }),
  family_no: varchar("family_no", { length: 20 }),
  hsp: varchar("hsp", { length: 70 }),
  cheque_no: varchar("cheque_no", { length: 20 }),
  cheque_date: varchar("cheque_date", { length: 20 }),
  cheque_desc: varchar("cheque_desc", { length: 30 }),
  uploaded: numeric("uploaded", { precision: 1, scale: 0 }),
  fms_pv_uploaded: numeric("fms_pv_uploaded", { precision: 1, scale: 0 }),
  pv_authorized: numeric("pv_authorized", { precision: 1, scale: 0 }),
  pv_authorized_date: date("pv_authorized_date"),
  pv_authorized_by: varchar("pv_authorized_by", { length: 100 }),
  old_amt_payable: numeric("old_amt_payable", { precision: 10, scale: 2 }),
  re_rate: numeric("re_rate", { precision: 5, scale: 0 }),
  re_recoverable_amt: numeric("re_recoverable_amt", {
    precision: 10,
    scale: 0,
  }),
  cheque_code: varchar("cheque_code", { length: 20 }),
  rejected_pv: numeric("rejected_pv", { precision: 1, scale: 0 }),
  category: varchar("category", { length: 10 }),
  sub_bene: numeric("sub_bene", { precision: 1, scale: 0 }),
  pri_dep: numeric("pri_dep", { precision: 2, scale: 0 }),
  smart_bill_id: varchar("smart_bill_id", { length: 20 }),
  wht_tax_rate: numeric("wht_tax_rate", { precision: 10, scale: 2 }),
  wht_tax_amt: numeric("wht_tax_amt", { precision: 10, scale: 2 }),
  net_amt_payable: numeric("net_amt_payable", { precision: 10, scale: 2 }),
  care_picked: numeric("care_picked", { precision: 1, scale: 0 }),
  upload_bills_smart: integer("upload_bills_smart"),
  copay_amt: numeric("copay_amt", { precision: 10, scale: 2 }),
  excess_amt: numeric("excess_amt", { precision: 10, scale: 2 }),
  excess_invoiced: integer("excess_invoiced"),
  excess_invoice_no: varchar("excess_invoice_no", { length: 20 }),
  excess_receipt_no: varchar("excess_receipt_no", { length: 50 }),
  excess_repaid_amt: numeric("excess_repaid_amt", { precision: 10, scale: 2 }),
  d_voucher: varchar("d_voucher", { length: 20 }),
  exgratia_amt: numeric("exgratia_amt", { precision: 18, scale: 2 }),
  rem_provider: integer("rem_provider"),
  rem_reason: integer("rem_reason"),
  rem_prov_proxy: varchar("rem_prov_proxy", { length: 70 }),
  foreign_amt: numeric("foreign_amt", { precision: 18, scale: 2 }),
  foreign_curr: integer("foreign_curr"),
  foreign_rate: numeric("foreign_rate", { precision: 18, scale: 2 }),
  re_assigned_to: varchar("re_assigned_to", { length: 15 }),
  re_assigned_on: date("re_assigned_on"),
  loss_date: date("loss_date"),
  service_description: varchar("service_description", { length: 255 }),
  voucher_batch_no: varchar("voucher_batch_no", { length: 200 }),
  is_foreign: numeric("is_foreign", { precision: 1, scale: 0 }),
});
