import {
  date,
  decimal,
  integer,
  numeric,
  pgTable,
  serial,
  varchar,
} from "drizzle-orm/pg-core";

export const corpGroups = pgTable("corp_groups", {
  idx: serial("idx").primaryKey(),
  corp_id: varchar("corp_id", { length: 10 }).notNull(),
  anniv: numeric("anniv", { precision: 2, scale: 0 }).notNull(),
  category: varchar("category", { length: 10 }).notNull(),
  benefit: numeric("benefit", { precision: 3, scale: 0 }).notNull(),
  fund: numeric("fund", { precision: 1, scale: 0 }),
  limit: numeric("limit", { precision: 10, scale: 2 }),
  sub_limit_of: numeric("sub_limit_of", { precision: 3, scale: 0 }),
  sharing: numeric("sharing", { precision: 1, scale: 0 }),
  sync: numeric("sync", { precision: 1, scale: 0 }),
  smart_sync: numeric("smart_sync", { precision: 1, scale: 0 }),
  utilize: numeric("utilize", { precision: 4, scale: 2 }),
  suspend_at: integer("suspend_at"),
  waiting_period: integer("waiting_period"),
  start_date: date("start_date"),
  end_date: date("end_date"),
  bed_limit: decimal("bed_limit", { precision: 18, scale: 2 }),
  allocate_to: integer("allocate_to"),
  allocated_to: integer("allocated_to"),
  ward_bed: integer("ward_bed"),
  group_limit: numeric("group_limit", { precision: 15, scale: 2 }),
  smart_picked: integer("smart_picked"),
  frequency: numeric("frequency", { precision: 5, scale: 0 }),
});
