import { date, numeric, pgTable, time, varchar } from "drizzle-orm/pg-core";

export const dummy = pgTable("dummy", {
  dental: varchar("dental", { length: 30 }),
  optical: varchar("optical", { length: 30 }),
  maternity: varchar("maternity", { length: 30 }),
  numeric_one: numeric("numeric_one", { precision: 10, scale: 2 }),
  numeric_two: numeric("numeric_two", { precision: 10, scale: 2 }),
  numeric_three: numeric("numeric_three", { precision: 10, scale: 2 }),
  numeric_four: numeric("numeric_four", { precision: 10, scale: 2 }),
  numeric_five: numeric("numeric_five", { precision: 10, scale: 2 }),
  numeric_six: numeric("numeric_six", { precision: 10, scale: 2 }),
  numeric_seven: numeric("numeric_seven", { precision: 10, scale: 2 }),
  date_one: date("date_one"),
  start_date: date("start_date"),
  end_date: date("end_date"),
  principal_name: varchar("principal_name", { length: 100 }),
  string_five: varchar("string_five", { length: 30 }),
  numeric_8: numeric("numeric_8", { precision: 10, scale: 0 }),
  string_six: varchar("string_six", { length: 30 }),
  string_seven: varchar("string_seven", { length: 60 }),
  string_eight: varchar("string_eight", { length: 60 }),
  string_9: varchar("string_9", { length: 60 }),
  string_10: varchar("string_10", { length: 10 }),
  string_11: varchar("string_11", { length: 70 }),
  string_12: varchar("string_12", { length: 30 }),
  string_13: varchar("string_13", { length: 10 }).primaryKey(),
  string_14: varchar("string_14", { length: 70 }),
  numeric_9: numeric("numeric_9", { precision: 5, scale: 0 }),
  numeric_10: numeric("numeric_10", { precision: 5, scale: 0 }),
  numeric_11: numeric("numeric_11", { precision: 5, scale: 0 }),
  numeric_12: numeric("numeric_12", { precision: 5, scale: 0 }),
  date_4: date("date_4"),
  numeric_14: numeric("numeric_14", { precision: 5, scale: 0 }),
  numeric_15: numeric("numeric_15", { precision: 5, scale: 0 }),
  numeric_16: numeric("numeric_16", { precision: 5, scale: 0 }),
  numeric_17: numeric("numeric_17", { precision: 5, scale: 0 }),
  string_15: varchar("string_15", { length: 10 }),
  date_5: date("date_5"),
  time_1: time("time_1"),
  date_6: date("date_6"),
  string_18: varchar("string_18", { length: 10 }),
  string_19: varchar("string_19", { length: 10 }),
  numeric_18: numeric("numeric_18", { precision: 5, scale: 0 }),
  num_19: numeric("num_19", { precision: 10, scale: 2 }),
  num_20: numeric("num_20", { precision: 10, scale: 2 }),
  num_21: numeric("num_21", { precision: 10, scale: 2 }),
  num_22: numeric("num_22", { precision: 10, scale: 2 }),
  num_23: numeric("num_23", { precision: 10, scale: 2 }),
  num_24: numeric("num_24", { precision: 10, scale: 2 }),
  family_no: varchar("family_no", { length: 20 }),
  member_no: varchar("member_no", { length: 20 }),
  scheme_no: varchar("scheme_no", { length: 20 }),
  surname: varchar("surname", { length: 60 }),
  first_name: varchar("first_name", { length: 60 }),
  other_names: varchar("other_names", { length: 60 }),
  mobile_no: varchar("mobile_no", { length: 30 }),
  dob: varchar("dob", { length: 30 }),
  idno: varchar("idno", { length: 30 }),
  pre_dep: varchar("pre_dep", { length: 30 }),
  gender: varchar("gender", { length: 30 }),
  category: varchar("category", { length: 30 }),
  corp_id: varchar("corp_id", { length: 30 }),
  fam_rela: varchar("fam_rela", { length: 30 }),
  idx: varchar("idx", { length: 20 }),
  voucher_no: varchar("voucher_no", { length: 20 }),
  voucher_date: date("voucher_date"),
  voucher_amt: numeric("voucher_amt", { precision: 10, scale: 2 }),
  payee_code: varchar("payee_code", { length: 20 }),
  payee_name: varchar("payee_name", { length: 100 }),
  user_id: varchar("user_id", { length: 100 }),
  inpatient: varchar("inpatient", { length: 20 }),
  outpatient: varchar("outpatient", { length: 20 }),
  corporate: varchar("corporate", { length: 100 }),
  policy_no: varchar("policy_no", { length: 20 }),
  member_name: varchar("member_name", { length: 100 }),
  provider: varchar("provider", { length: 100 }),
  invoice_date: date("invoice_date"),
  invoice_no: varchar("invoice_no", { length: 50 }),
  invoice_amount: numeric("invoice_amount", { precision: 10, scale: 0 }),
  link: numeric("link", { precision: 5, scale: 0 }),
  error_desc: varchar("error_desc", { length: 100 }),
  claim_no: varchar("claim_no", { length: 50 }),
  paid_amt: numeric("paid_amt", { precision: 10, scale: 2 }),
  recover_rate: numeric("recover_rate", { precision: 10, scale: 2 }),
  recover_amt: numeric("recover_amt", { precision: 10, scale: 2 }),
  benefit: varchar("benefit", { length: 50 }),
  insured: varchar("insured", { length: 50 }),
  gross_prem: numeric("gross_prem", { precision: 10, scale: 2 }),
  cede_prem: numeric("cede_prem", { precision: 10, scale: 2 }),
  commission_amt: numeric("commission_amt", { precision: 10, scale: 2 }),
  prem_tax: numeric("prem_tax", { precision: 10, scale: 2 }),
  cheque_no: varchar("cheque_no", { length: 20 }),
  claimant: varchar("claimant", { length: 60 }),
  cheque_amt: numeric("cheque_amt", { precision: 10, scale: 2 }),
  cheque_date: date("cheque_date"),
  client: varchar("client", { length: 50 }),
  trans_date: date("trans_date"),
  transaction: varchar("transaction", { length: 20 }),
  debit_gross: numeric("debit_gross", { precision: 10, scale: 2 }),
  phcf: numeric("phcf", { precision: 10, scale: 2 }),
  tl: numeric("tl", { precision: 10, scale: 2 }),
  sd: numeric("sd", { precision: 10, scale: 2 }),
  debit: numeric("debit", { precision: 10, scale: 2 }),
  credit: numeric("credit", { precision: 10, scale: 2 }),
  ip_prem: numeric("ip_prem", { precision: 10, scale: 2 }),
  op_prem: numeric("op_prem", { precision: 10, scale: 2 }),
  tax: numeric("tax", { precision: 10, scale: 2 }),
  net_premium: numeric("net_premium", { precision: 10, scale: 2 }),
  principal: varchar("principal", { length: 70 }),
  renewal_date: date("renewal_date"),
  anniv: numeric("anniv", { precision: 3, scale: 0 }),
  date_received: date("date_received"),
  batch_no: varchar("batch_no", { length: 20 }),
  batch_user: varchar("batch_user", { length: 10 }),
  claims_count: numeric("claims_count", { precision: 20, scale: 0 }),
  data_entrant: varchar("data_entrant", { length: 10 }),
  entrant_date: date("entrant_date"),
  vetter: varchar("vetter", { length: 10 }),
  vetting_date: date("vetting_date"),
  authoriser: varchar("authoriser", { length: 10 }),
  authorising_date: date("authorising_date"),
  finance: varchar("finance", { length: 10 }),
  finance_date: date("finance_date"),
  batch_period: numeric("batch_period", { precision: 3, scale: 0 }),
  personal_accident: varchar("personal_accident", { length: 10 }),
  last_expense: varchar("last_expense", { length: 10 }),
  pre_existing_diagnosis: varchar("pre_existing_diagnosis", { length: 10 }),
  congenital: varchar("congenital", { length: 10 }),
  psychiatric: varchar("psychiatric", { length: 10 }),
  first_emergency_cs: varchar("first_emergency_cs", { length: 10 }),
  ip_non_accidental_dental: varchar("ip_non_accidental_dental", { length: 10 }),
  ip_non_accidental_optical: varchar("ip_non_accidental_optical", {
    length: 10,
  }),
  post_hospitalization: varchar("post_hospitalization", { length: 10 }),
  inpatient_and_outpatient: varchar("inpatient_and_outpatient", { length: 10 }),
  dental_optical: varchar("dental_optical", { length: 10 }),
  batch_date: date("batch_date"),
  proxy_payee: varchar("proxy_payee", { length: 20 }),
  bill_amt: numeric("bill_amt", { precision: 10, scale: 2 }),
  string_one: varchar("string_one", { length: 50 }),
  string_two: varchar("string_two", { length: 50 }),
  string_three: varchar("string_three", { length: 50 }),
});
