import {
  date,
  decimal,
  integer,
  numeric,
  pgTable,
  serial,
  varchar,
} from "drizzle-orm/pg-core";

export const member_benefits = pgTable("member_benefits", {
  idx: serial("idx").primaryKey(),
  member_no: varchar("member_no", { length: 20 }).notNull(),
  benefit: numeric("benefit", { precision: 3 }).notNull(),
  limit: numeric("limit", { precision: 10, scale: 2 }),
  sharing: numeric("sharing", { precision: 1 }),
  re_insurer: numeric("re_insurer", { precision: 2 }),
  anniv: numeric("anniv", { precision: 2 }).notNull(),
  sub_limit_of: numeric("sub_limit_of", { precision: 3 }),
  suspended: numeric("suspended", { precision: 1 }),
  category: varchar("category", { length: 10 }),
  fund: numeric("fund", { precision: 1 }),
  suspended_date: date("suspended_date"),
  capitated: numeric("capitated", { precision: 1 }),
  waiting_period: numeric("waiting_period", { precision: 3 }),
  utilize: numeric("utilize", { precision: 3, scale: 2 }),
  expense: numeric("expense", { precision: 10, scale: 2 }),
  balance: numeric("balance", { precision: 10, scale: 2 }),
  threshold: numeric("threshold", { precision: 10, scale: 2 }),
  care_picked: numeric("care_picked", { precision: 1 }),
  reserve_amt: decimal("reserve_amt", { precision: 10, scale: 2 }),
  smart_sync: integer("smart_sync"),
  sync: integer("sync"),
  suspend_at: integer("suspend_at"),
  bed_limit: decimal("bed_limit", { precision: 10, scale: 2 }),
  group_limit: numeric("group_limit", { precision: 15, scale: 2 }),
  frequency: numeric("frequency", { precision: 5 }),
});
