import {
  date,
  integer,
  numeric,
  pgTable,
  serial,
  timestamp,
  varchar,
} from "drizzle-orm/pg-core";

export const member_info = pgTable("member_info", {
  idx: serial("idx").primaryKey(),
  family_no: varchar("family_no", { length: 20 }).notNull(),
  member_no: varchar("member_no", { length: 20 }).notNull(),
  surname: varchar("surname", { length: 40 }),
  first_name: varchar("first_name", { length: 40 }),
  other_names: varchar("other_names", { length: 40 }),
  dob: date("dob"),
  occupation: numeric("occupation", { precision: 2 }),
  id_pp_no: varchar("id_pp_no", { length: 15 }),
  blood_group: numeric("blood_group", { precision: 2 }),
  relation_to_principal: numeric("relation_to_principal", { precision: 2 }),
  user_id: varchar("user_id", { length: 100 }),
  date_entered: timestamp("date_entered").notNull().defaultNow(),
  family_title: numeric("family_title", { precision: 2 }),
  dealing_user: varchar("dealing_user", { length: 10 }),
  cancelled: numeric("cancelled", { precision: 1 }),
  employment_no: varchar("employment_no", { length: 30 }),
  gender: numeric("gender", { precision: 1 }),
  card_to_member: date("card_to_member"),
  passport_no: varchar("passport_no", { length: 15 }),
  nhif_card_no: varchar("nhif_card_no", { length: 15 }),
  height: varchar("height", { length: 10 }),
  weight: varchar("weight", { length: 10 }),
  photo_n_form: numeric("photo_n_form", { precision: 1 }),
  photo_no: numeric("photo_no", { precision: 5 }),
  info_to_printer: date("info_to_printer"),
  card_from_printer: date("card_from_printer"),
  app_form_date: date("app_form_date"),
  marital_status: numeric("marital_status", { precision: 1 }),
  date_employed: date("date_employed"),
  member_id: varchar("member_id", { length: 20 }),
  corp_id: varchar("corp_id", { length: 5 }),
  family_size: numeric("family_size", { precision: 2 }),
  mem_pin: varchar("mem_pin", { length: 50 }),
  single_parent: numeric("single_parent", { precision: 1 }),
  care_picked: numeric("care_picked", { precision: 1 }),
  age: integer("age"),
  card_serial_no: varchar("card_serial_no", { length: 50 }),
  excempt_cut: integer("excempt_cut"),
  vip: numeric("vip", { precision: 1 }),
  smart_sync: integer("smart_sync"),
  smart_picked: integer("smart_picked"),
  cat_change_picked: integer("cat_change_picked"),
  insurer: numeric("insurer", { precision: 5 }),
});
