import { date, numeric, pgTable, serial, varchar } from "drizzle-orm/pg-core";

export const chequePayment = pgTable("cheque_payment", {
  payment_no: serial("payment_no").primaryKey(),
  cheque_no: varchar("cheque_no", { length: 10 }),
  cheque_date: date("cheque_date"),
  cheque_amount: numeric("cheque_amount", { precision: 10, scale: 2 }),
  payee: varchar("payee", { length: 100 }),
  payee_type: numeric("payee_type", { precision: 3, scale: 0 }),
  dispatched: numeric("dispatched", { precision: 1, scale: 0 }),
  date_dispatched: date("date_dispatched"),
  user_id: varchar("user_id", { length: 100 }),
  date_entered: date("date_entered").notNull().defaultNow(),
  deduction: numeric("deduction", { precision: 10, scale: 2 }),
  vno_ovrd: varchar("vno_ovrd", { length: 10 }),
  pno_ovrd: numeric("pno_ovrd", { precision: 10, scale: 0 }),
  pay_ovrd: numeric("pay_ovrd", { precision: 1, scale: 0 }),
  override_amt: numeric("override_amt", { precision: 10, scale: 2 }),
  vno_ovrd_exec: varchar("vno_ovrd_exec", { length: 10 }),
  pno_ovrd_exec: numeric("pno_ovrd_exec", { precision: 10, scale: 0 }),
  pay_ovrd_exec: numeric("pay_ovrd_exec", { precision: 1, scale: 0 }),
  override_amt_exec: numeric("override_amt_exec", { precision: 10, scale: 2 }),
  total_commission: numeric("total_commission", { precision: 10, scale: 2 }),
  wh_tax_rate: numeric("wh_tax_rate", { precision: 10, scale: 2 }),
  wh_tax_amt: numeric("wh_tax_amt", { precision: 10, scale: 2 }),
  override_rate: numeric("override_rate", { precision: 10, scale: 2 }),
  commis_deduction: numeric("commis_deduction", { precision: 10, scale: 2 }),
  agent_id: varchar("agent_id", { length: 10 }),
});
