import { date, numeric, pgTable, serial, varchar } from "drizzle-orm/pg-core";

export const member_medical = pgTable("member_medical", {
  idx: serial("idx").primaryKey(),
  member_no: varchar("member_no", { length: 20 }),
  anniv: numeric("anniv", { precision: 2 }),
  asthma: numeric("asthma", { precision: 1 }),
  diabetes: numeric("diabetes", { precision: 1 }),
  hypertension: numeric("hypertension", { precision: 1 }),
  convulsion_epilepsy: numeric("convulsion_epilepsy", { precision: 1 }),
  gastric_duodenal_ulcers: numeric("gastric_duodenal_ulcers", { precision: 1 }),
  heart_disease: numeric("heart_disease", { precision: 1 }),
  neurological_disease: numeric("neurological_disease", { precision: 1 }),
  currently_ill: numeric("currently_ill", { precision: 1 }),
  current_ill_details: varchar("current_ill_details", { length: 300 }),
  gallstones: numeric("gallstones", { precision: 1 }),
  recent_consulted_doc: numeric("recent_consulted_doc", { precision: 1 }),
  recent_consulted_details: varchar("recent_consulted_details", {
    length: 300,
  }),
  diabled: numeric("diabled", { precision: 1 }),
  disability_details: varchar("disability_details", { length: 30 }),
  past_deliveries: numeric("past_deliveries", { precision: 2 }),
  normal: numeric("normal", { precision: 2 }),
  caesarian: numeric("caesarian", { precision: 2 }),
  expectant: numeric("expectant", { precision: 1 }),
  expected_delivery_date: date("expected_delivery_date"),
  psychiatric_illness: numeric("psychiatric_illness", { precision: 1 }),
  recurrent_tonsillitis: numeric("recurrent_tonsillitis", { precision: 1 }),
  arthritis_fibroids: numeric("arthritis_fibroids", { precision: 1 }),
  menstrual_disorder: numeric("menstrual_disorder", { precision: 1 }),
  cancer: numeric("cancer", { precision: 1 }),
  smokes: numeric("smokes", { precision: 1 }),
  takes_alcohol: numeric("takes_alcohol", { precision: 1 }),
  on_regular_medication: numeric("on_regular_medication", { precision: 1 }),
  regular_medication_details: varchar("regular_medication_details", {
    length: 300,
  }),
  future_hospitalization: varchar("future_hospitalization", { length: 30 }),
  current_doctor: varchar("current_doctor", { length: 30 }),
});
